package com.example.fashion_recommender.contoroller;

import com.atilika.kuromoji.ipadic.Token;
import com.atilika.kuromoji.ipadic.Tokenizer;
import okhttp3.*;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.Map.Entry;

@Controller
public class FashionRecommenderController {

    private String brandName1;
    private String brandName2;
    private String brandName3;

    OkHttpClient client = new OkHttpClient();

    private String run(String url) throws IOException {
        Request request = new Request.Builder().url(url).build();
        try (Response response = client.newCall(request).execute()) {
            return response.body().string();
        }
    }

    private Tokenizer makeTokenizer(String userDictionaryEntry) throws IOException {
        return new Tokenizer.Builder()
                .userDictionary(
                        makeUserDictionaryStream(userDictionaryEntry)
                )
                .build();
    }
    private ByteArrayInputStream makeUserDictionaryStream(String userDictionary) {
        return new ByteArrayInputStream(
                userDictionary.getBytes(StandardCharsets.UTF_8)
        );
    }

    @GetMapping("/top")
    public String getTop(Model model) {
        model.addAttribute("title", "検索フォーム");
        return "top.html";
    }

    @PostMapping("/top")
    public String postTop(@RequestParam("keyword") String keyword) throws IOException {

        Map<String, Integer> countBrandName = new HashMap<>();

//        フォームに入力されたキーワードで、50件の検索結果を取得
        String url = "https://www.google.co.jp/search?hl=ja&num=50&q=" + keyword + "+ファッション+ブランド";

//        HTTPリクエスト
        String html = this.run(url);

//        HTMLパース
        Document doc = Jsoup.parse(html);
        Element link = doc.select("a").first();

//        記述されているテキストの取得
        String resultHtmlText = doc.body().text();

//        形態素解析
        Tokenizer tokenizer = makeTokenizer(userDictionary);

        List<Token> tokens = tokenizer.tokenize(resultHtmlText);

        for (Token token : tokens) {
            if(token.getPartOfSpeechLevel1().equals("カスタム名詞")){

                if (countBrandName.get(token.getSurface()) == null) {
                    countBrandName.put(token.getSurface(), 1);
                }else{
                    Integer value = countBrandName.get(token.getSurface());
                    countBrandName.put(token.getSurface(), value + 1);
                }
            }
        }

        List<Entry<String, Integer>> list = new ArrayList<>(countBrandName.entrySet());
        list.sort(Entry.comparingByValue(Comparator.reverseOrder()));

        this.brandName1 = list.get(0).getKey();
        this.brandName2 = list.get(1).getKey();
        this.brandName3 = list.get(2).getKey();
        return "redirect:/result";
    }
    @GetMapping("/result")
    public String getResult(Model model) {
        model.addAttribute("brandName1", this.brandName1);
        model.addAttribute("brandName2", this.brandName2);
        model.addAttribute("brandName3", this.brandName3);
        return "result.html";
    }

//    辞書
    private String userDictionary =
        "コムデギャルソン,コムデギャルソン,コムデギャルソン,カスタム名詞\n" +
        "COMMEdesGARCONS,COMMEdesGARCONS,コムデギャルソン,カスタム名詞\n" +
        "ヨウジヤマモト,ヨウジヤマモト,ヨウジヤマモト,カスタム名詞\n" +
        "YohjiYamamoto,YohjiYamamoto,ヨウジヤマモト,カスタム名詞" +
        "ABATHINGAPE,ABATHINGAPE,アベイシングエイプ,カスタム名詞\n" +
        "A.P.C.,A.P.C.,エーピーシー,カスタム名詞\n" +
        "AcneStudios,AcneStudios,アクネストゥディオズ,カスタム名詞\n" +
        "ADAMETROPE,ADAMETROPE,アダムエロペ,カスタム名詞\n" +
        "ADDICTION,ADDICTION,アディクション,カスタム名詞\n" +
        "adidas,adidas,アディダス,カスタム名詞\n" +
        "Aesop,Aesop,イソップ,カスタム名詞\n" +
        "Aeta,Aeta,アエタ,カスタム名詞\n" +
        "agnesb.,agnesb.,アニエスベー,カスタム名詞\n" +
        "AGNONA,AGNONA,アニョーナ,カスタム名詞\n" +
        "AHKAH,AHKAH,アーカー,カスタム名詞\n" +
        "AKANEUTSUNOMIYA,AKANEUTSUNOMIYA,ウツノミヤアカネ,カスタム名詞\n" +
        "AKIKOAOKI,AKIKOAOKI,アキコアオキ,カスタム名詞\n" +
        "AKIRANAKA,AKIRANAKA,アキラナカ,カスタム名詞\n" +
        "ALAIA,ALAIA,アライア,カスタム名詞\n" +
        "alainmikli,alainmikli,アランミクリ,カスタム名詞\n" +
        "ALANUI,ALANUI,アラヌイ,カスタム名詞\n" +
        "ALBERTAFERRETTI,ALBERTAFERRETTI,アルベルタフェレッティ,カスタム名詞\n" +
        "ALBION,ALBION,アルビオン,カスタム名詞\n" +
        "ALDEN,ALDEN,オールデン,カスタム名詞\n" +
        "ALETTEBLANC,ALETTEBLANC,アレットブラン,カスタム名詞\n" +
        "AlexanderMcQueen,AlexanderMcQueen,アレキサンダーマックイーン,カスタム名詞\n" +
        "alexanderwang,alexanderwang,アレキサンダーワン,カスタム名詞\n" +
        "ALEXISMABILLE,ALEXISMABILLE,アレクシスマビユ,カスタム名詞\n" +
        "aliceolivia,aliceolivia,アリスアンドオリビア,カスタム名詞\n" +
        "aliceauaa,aliceauaa,アリスアウアア,カスタム名詞\n" +
        "ALLEGE,ALLEGE,アレッジ,カスタム名詞\n" +
        "AMACA,AMACA,アマカ,カスタム名詞\n" +
        "AMBELL,AMBELL,アンベル,カスタム名詞\n" +
        "AMBUSH,AMBUSH,アンブッシュ,カスタム名詞\n" +
        "AMIPARIS,AMIPARIS,アミパリ,カスタム名詞\n" +
        "amiu.c,amiu.c,アミユシー,カスタム名詞\n" +
        "ANDERSEN-ANDERSEN,ANDERSEN-ANDERSEN,アンデルセンアンデルセン,カスタム名詞\n" +
        "aniary,aniary,アニアリ,カスタム名詞\n" +
        "ANNDEMEULEMEESTER,ANNDEMEULEMEESTER,アンドゥムルメステール,カスタム名詞\n" +
        "ANNASUI,ANNASUI,アナスイ,カスタム名詞\n" +
        "ANREALAGE,ANREALAGE,アンリアレイジュ,カスタム名詞\n" +
        "ANTEPRIMA,ANTEPRIMA,アンテプリマ,カスタム名詞\n" +
        "ANTHEMA,ANTHEMA,アンセムエー,カスタム名詞\n" +
        "ANTIPAST,ANTIPAST,アンティパスト,カスタム名詞\n" +
        "ANYAHINDMARCH,ANYAHINDMARCH,アニヤハインドマーチ,カスタム名詞\n" +
        "APOCRYPHA.,APOCRYPHA.,アポクリファ,カスタム名詞\n" +
        "Aquascutum,Aquascutum,アクアスキュータム,カスタム名詞\n" +
        "aramis,aramis,アラミス,カスタム名詞\n" +
        "ARC'TERYX,ARC'TERYX,アークテリクス,カスタム名詞\n" +
        "Arobe,Arobe,アローブ,カスタム名詞\n" +
        "ASEEDONCLOUD,ASEEDONCLOUD,アシードオンクラウド,カスタム名詞\n" +
        "ASICS,ASICS,アシックス,カスタム名詞\n" +
        "atmos,atmos,アトモス,カスタム名詞\n" +
        "ato,ato,アトウ,カスタム名詞\n" +
        "ATSUSHINAKASHIMA,ATSUSHINAKASHIMA,ナカシマアツシ,カスタム名詞\n" +
        "ATTACHMENT,ATTACHMENT,アタッチメント,カスタム名詞\n" +
        "AUBERCY,AUBERCY,オーベルシー,カスタム名詞\n" +
        "AUDEMARSPIGUE,AUDEMARSPIGUE,オーデマピゲ,カスタム名詞\n" +
        "AULA,AULA,アウラ,カスタム名詞\n" +
        "AURALEE,AURALEE,オーラリー,カスタム名詞\n" +
        "AUTHENTICSHOE&Co.,AUTHENTICSHOE&Co.,オーセンティックシューアンドコー,カスタム名詞\n" +
        "AVIE,AVIE,アヴィ,カスタム名詞\n" +
        "AYAME,AYAME,アヤメ,カスタム名詞\n" +
        "ayameiweardesign,ayameiweardesign,アヤメアイウェアデザイン,カスタム名詞\n" +
        "ayumi.mitsukane,ayumi.mitsukane,アユミミツカネ,カスタム名詞\n" +
        "AYURA,AYURA,アユラ,カスタム名詞\n" +
        "AZULbymoussy,AZULbymoussy,アズールバイマウジー,カスタム名詞\n" +
        "ARMANIEXCHANGE,ARMANIEXCHANGE,アーエックスアルマーニエクスチェンジ,カスタム名詞\n" +
        "B.A,B.A,ビーエー,カスタム名詞\n" +
        "babaco,babaco,ババコ,カスタム名詞\n" +
        "Baccarat,Baccarat,バカラ,カスタム名詞\n" +
        "BALENCIAGA,BALENCIAGA,バレンシアガ,カスタム名詞\n" +
        "Bally,Bally,バリー,カスタム名詞\n" +
        "BALMAIN,BALMAIN,バルマン,カスタム名詞\n" +
        "BALMUNG,BALMUNG,バルムンク,カスタム名詞\n" +
        "Barbour,Barbour,バブアー,カスタム名詞\n" +
        "BASICKS,BASICKS,ベーシックス,カスタム名詞\n" +
        "BATONER,BATONER,バトナー,カスタム名詞\n" +
        "BAUMUNDPFERDGARTEN,BAUMUNDPFERDGARTEN,バウムウントフェルトガルテン,カスタム名詞\n" +
        "BEAMS,BEAMS,ビームス,カスタム名詞\n" +
        "beautifulpeople,beautifulpeople,ビューティフルピープル,カスタム名詞\n" +
        "BEDj.w.FORD,BEDj.w.FORD,ベッドジェイダブリューフォード,カスタム名詞\n" +
        "bedsidedrama,bedsidedrama,ベッドサイドドラマ,カスタム名詞\n" +
        "BEDWIN&THEHEARTBREAKERS,BEDWIN&THEHEARTBREAKERS,ベドウィンアンドザハートブレイカーズ,カスタム名詞\n" +
        "Belstaff,Belstaff,ベルスタッフ,カスタム名詞\n" +
        "BENTAVERNITIUNRAVELPROJECT,BENTAVERNITIUNRAVELPROJECT,ベンタバーニティアンラベルプロジェクト,カスタム名詞\n" +
        "bench,bench,ベンチ,カスタム名詞\n" +
        "BERING,BERING,ベリング,カスタム名詞\n" +
        "BERLUTI,BERLUTI,ベルルッティ,カスタム名詞\n" +
        "Bershka,Bershka,ベルシュカ,カスタム名詞\n" +
        "BESPOKETOKYO,BESPOKETOKYO,ベスポークトーキョー,カスタム名詞\n" +
        "BIRKENSTOCK,BIRKENSTOCK,ビルケンシュトック,カスタム名詞\n" +
        "BlackWeirdos,BlackWeirdos,ブラックウィアードス,カスタム名詞\n" +
        "blugirl,blugirl,ブルガール,カスタム名詞\n" +
        "Blumarine,Blumarine,ブルマリン,カスタム名詞\n" +
        "blurhms,blurhms,ブラームス,カスタム名詞\n" +
        "BOBBIBROWN,BOBBIBROWN,ボビーブラウン,カスタム名詞\n" +
        "BODHI,BODHI,ボディ,カスタム名詞\n" +
        "BODYSONG.,BODYSONG.,ボディソング,カスタム名詞\n" +
        "Bonpoint,Bonpoint,ボンポワン,カスタム名詞\n" +
        "Borsalino,Borsalino,ボルサリーノ,カスタム名詞\n" +
        "BOTANIST,BOTANIST,ボタニスト,カスタム名詞\n" +
        "BOTTEGAVENETA,BOTTEGAVENETA,ボッテガヴェネタ,カスタム名詞\n" +
        "BOUNTYHUNTER,BOUNTYHUNTER,バウンティハンター,カスタム名詞\n" +
        "BRACTMENT,BRACTMENT,ブラクトメント,カスタム名詞\n" +
        "Breguet,Breguet,ブレゲ,カスタム名詞\n" +
        "BREITLING,BREITLING,ブライトリング,カスタム名詞\n" +
        "BrooksBrothers,BrooksBrothers,ブルックスブラザーズ,カスタム名詞\n" +
        "BRUNELLOCUCINELLI,BRUNELLOCUCINELLI,ブルネロクチネリ,カスタム名詞\n" +
        "bubóBARCELONA,bubóBARCELONA,ブボバルセロナ,カスタム名詞\n" +
        "bukht,bukht,ブクト,カスタム名詞\n" +
        "BURBERRY,BURBERRY,バーバリー,カスタム名詞\n" +
        "BUTTERO,BUTTERO,ブッテロ,カスタム名詞\n" +
        "BVLGARI,BVLGARI,ブルガリ,カスタム名詞\n" +
        "BYREDO,BYREDO,バイレド,カスタム名詞\n" +
        "C.P.COMPANY,C.P.COMPANY,シーピーカンパニー,カスタム名詞\n" +
        "CalvinKlein,CalvinKlein,カルバンクライン,カスタム名詞\n" +
        "CAMPER,CAMPER,カンペール,カスタム名詞\n" +
        "CANADAGOOSE,CANADAGOOSE,カナダグース,カスタム名詞\n" +
        "CANALI,CANALI,カナリ,カスタム名詞\n" +
        "CandyStripper,CandyStripper,キャンディストリッパー,カスタム名詞\n" +
        "CANMAKE,CANMAKE,キャンメイク,カスタム名詞\n" +
        "CAROLCHRISTIANPOELL,CAROLCHRISTIANPOELL,キャロルクリスチャンプエル,カスタム名詞\n" +
        "Cartier,Cartier,カルティエ,カスタム名詞\n" +
        "CARVEN,CARVEN,カルヴェン,カスタム名詞\n" +
        "CathKidston,CathKidston,キャスキッドソン,カスタム名詞\n" +
        "CEDRICCHARLIER,CEDRICCHARLIER,セドリックシャルリエ,カスタム名詞\n" +
        "CELINE,CELINE,セリーヌ,カスタム名詞\n" +
        "Celvoke,Celvoke,セルヴォーク,カスタム名詞\n" +
        "CFCL,CFCL,シーエフシーエル,カスタム名詞\n" +
        "Champion,Champion,チャンピオン,カスタム名詞\n" +
        "CHANLUU,CHANLUU,チャンルー,カスタム名詞\n" +
        "CHANEL,CHANEL,シャネル,カスタム名詞\n" +
        "CHAUMET,CHAUMET,ショーメ,カスタム名詞\n" +
        "ChikaKisada,ChikaKisada,チカキサダ,カスタム名詞\n" +
        "Childrenofthediscordance,Childrenofthediscordance,チルドレンオブザディスコーダンス,カスタム名詞\n" +
        "Chloe,Chloe,クロエ,カスタム名詞\n" +
        "Chopard,Chopard,ショパール,カスタム名詞\n" +
        "ChristianLouboutin,ChristianLouboutin,クリスチャンルブタン,カスタム名詞\n" +
        "ChristopherKane,ChristopherKane,クリストファーケイン,カスタム名詞\n" +
        "CHROMEHEARTS,CHROMEHEARTS,クロムハーツ,カスタム名詞\n" +
        "ChunShuiTang,ChunShuiTang,チュンシュイタン,カスタム名詞\n" +
        "Church's,Church's,チャーチ,カスタム名詞\n" +
        "CINOH,CINOH,チノ,カスタム名詞\n" +
        "CINQUANTA,CINQUANTA,チンクアンタ,カスタム名詞\n" +
        "CITIZEN,CITIZEN,シチズン,カスタム名詞\n" +
        "CITY,CITY,シティ,カスタム名詞\n" +
        "CIVILIZED,CIVILIZED,シヴィライズド,カスタム名詞\n" +
        "CLANE,CLANE,クラネ,カスタム名詞\n" +
        "CLARINS,CLARINS,クラランス,カスタム名詞\n" +
        "CLAUDIALI,CLAUDIALI,クラウディアリ,カスタム名詞\n" +
        "cledepeauBeautE,cledepeauBeautE,クレ・ド・ポーボーテ,カスタム名詞\n" +
        "CLINIQUE,CLINIQUE,クリニーク,カスタム名詞\n" +
        "CMMNSWDN,CMMNSWDN,コモンスウェデン,カスタム名詞\n" +
        "COACH,COACH,コーチ,カスタム名詞\n" +
        "Cocilaelle,Cocilaelle,コキラエル,カスタム名詞\n" +
        "coeur,coeur,クール,カスタム名詞\n" +
        "COFFRETD'OR,COFFRETD'OR,コフレドール,カスタム名詞\n" +
        "Columbia,Columbia,コロンビア,カスタム名詞\n" +
        "COMESANDGOES,COMESANDGOES,カムズアンドゴーズ,カスタム名詞\n" +
        "COMMEdesGARÇONS,COMMEdesGARÇONS,コムデギャルソン,カスタム名詞\n" +
        "COMOLI,COMOLI,コモリ,カスタム名詞\n" +
        "CONVERSE,CONVERSE,コンバース,カスタム名詞\n" +
        "COOHEM,COOHEM,クーヘム,カスタム名詞\n" +
        "COS,COS,コス,カスタム名詞\n" +
        "CoSTUMENATIONAL,CoSTUMENATIONAL,コスチュームナショナル,カスタム名詞\n" +
        "COVERMARK,COVERMARK,カバーマーク,カスタム名詞\n" +
        "Credor,Credor,クレドール,カスタム名詞\n" +
        "CROCKETT&JONES,CROCKETT&JONES,クロケットアンドジョーンズ,カスタム名詞\n" +
        "Cruciani,Cruciani,クルチアーニ,カスタム名詞\n" +
        "CULLNI,CULLNI,カルニ,カスタム名詞\n" +
        "CUNE,CUNE,クネ,カスタム名詞\n" +
        "CYCLAS,CYCLAS,サイクラス,カスタム名詞\n" +
        "D'URBAN,D'URBAN,ディアーバン,カスタム名詞\n" +
        "DAIRIKU,DAIRIKU,ダイリク,カスタム名詞\n" +
        "DAKS,DAKS,ダックス,カスタム名詞\n" +
        "Daniel&Bob,Daniel&Bob,ダニエルアンドボブ,カスタム名詞\n" +
        "DELAMER,DELAMER,ドゥラメール,カスタム名詞\n" +
        "DECORTE,DECORTE,デコルテ,カスタム名詞\n" +
        "DEMEL,DEMEL,デメル,カスタム名詞\n" +
        "DENHAM,DENHAM,デンハム,カスタム名詞\n" +
        "DEPAREILLE,DEPAREILLE,デパレイエ,カスタム名詞\n" +
        "DEREKLAM,DEREKLAM,デレクラム,カスタム名詞\n" +
        "DESCENTE,DESCENTE,デサント,カスタム名詞\n" +
        "DIANA,DIANA,ディアナ,カスタム名詞\n" +
        "DIANEvonFURSTENBERG,DIANEvonFURSTENBERG,ダイアンフォンファステンバーグ,カスタム名詞\n" +
        "Dickies,Dickies,ディッキーズ,カスタム名詞\n" +
        "DIESEL,DIESEL,ディーゼル,カスタム名詞\n" +
        "DIESELBLACKGOLD,DIESELBLACKGOLD,ディーゼルブラックゴールド,カスタム名詞\n" +
        "DIETBUTCHER,DIETBUTCHER,ダイエットブッチャー,カスタム名詞\n" +
        "DIGAWEL,DIGAWEL,ディガウェル,カスタム名詞\n" +
        "DIOR,DIOR,ディオール,カスタム名詞\n" +
        "DIORHOMME,DIORHOMME,ディオールオム,カスタム名詞\n" +
        "Diptyque,Diptyque,ディプティック,カスタム名詞\n" +
        "discordYohjiYamamoto,discordYohjiYamamoto,ディスコードヨウジヤマモト,カスタム名詞\n" +
        "DISCOVERED,DISCOVERED,ディスカバード,カスタム名詞\n" +
        "DITA,DITA,ディータ,カスタム名詞\n" +
        "divka,divka,ディフカ,カスタム名詞\n" +
        "DOLCE&GABBANA,DOLCE&GABBANA,ドルチェアンドガッバーナ,カスタム名詞\n" +
        "doublet,doublet,ダブレット,カスタム名詞\n" +
        "Dr.Martens,Dr.Martens,ドクターマーチン,カスタム名詞\n" +
        "DRESSEDUNDRESSED,DRESSEDUNDRESSED,ドレスドアンドドレスド,カスタム名詞\n" +
        "DRIESVANNOTEN,DRIESVANNOTEN,ドリスヴァンノッテン,カスタム名詞\n" +
        "DSQUARED2,DSQUARED2,ディースクエアード2,カスタム名詞\n" +
        "DUELLUM,DUELLUM,デュエルム,カスタム名詞\n" +
        "dunhill,dunhill,ダンヒル,カスタム名詞\n" +
        "DUVETICA,DUVETICA,デュベティカ,カスタム名詞\n" +
        "e.m.,e.m.,イーエム,カスタム名詞\n" +
        "EACHOTHER,EACHOTHER,イーチアザー,カスタム名詞\n" +
        "EBONY,EBONY,エボニー,カスタム名詞\n" +
        "EDROBERTJUDSON,EDROBERTJUDSON,エドロバートジャドソン,カスタム名詞\n" +
        "EDWARDGREEN,EDWARDGREEN,エドワードグリーン,カスタム名詞\n" +
        "EDWIN,EDWIN,エドウィン,カスタム名詞\n" +
        "EFFECTEN,EFFECTEN,エフェクテン,カスタム名詞\n" +
        "EFILEVOL,EFILEVOL,イフィールヴォル,カスタム名詞\n" +
        "Eggs'nThings,Eggs'nThings,エッグスンシングス,カスタム名詞\n" +
        "elephantTRIBALfabrics,elephantTRIBALfabrics,エレファントトライバルファブリックス,カスタム名詞\n" +
        "ELISABETTAFRANCHI,ELISABETTAFRANCHI,エリザベッタフランキ,カスタム名詞\n" +
        "ElizabethandJames,ElizabethandJames,エリザベスアンドジェームズ,カスタム名詞\n" +
        "EMILIOPUCCI,EMILIOPUCCI,エミリオプッチ,カスタム名詞\n" +
        "EmilyTemplecute,EmilyTemplecute,エミリーテンプルキュート,カスタム名詞\n" +
        "EMMETI,EMMETI,エンメティ,カスタム名詞\n" +
        "emmi,emmi,エミー,カスタム名詞\n" +
        "EMPORIOARMANI,EMPORIOARMANI,エンポリオアルマーニ,カスタム名詞\n" +
        "ENFOLD,ENFOLD,エンフォルド,カスタム名詞\n" +
        "ENGINEEREDGARMENTS,ENGINEEREDGARMENTS,エンジニアードガーメンツ,カスタム名詞\n" +
        "EnharmonicTAVERN,EnharmonicTAVERN,エンハーモニックタバーン,カスタム名詞\n" +
        "EPOCA,EPOCA,エポカ,カスタム名詞\n" +
        "EQUIPMENT,EQUIPMENT,エクイップメント,カスタム名詞\n" +
        "ERDEM,ERDEM,エルデム,カスタム名詞\n" +
        "ERMANNOSCERVINO,ERMANNOSCERVINO,エルマノスチェルヴィノ,カスタム名詞\n" +
        "ESLOW,ESLOW,エスロウ,カスタム名詞\n" +
        "ESPRIQUE,ESPRIQUE,エスプリーク,カスタム名詞\n" +
        "est,est,エスト,カスタム名詞\n" +
        "EsteeLauder,EsteeLauder,エスティローダー,カスタム名詞\n" +
        "ESTNATION,ESTNATION,エストネーション,カスタム名詞\n" +
        "ETHOSENS,ETHOSENS,エトーセンス,カスタム名詞\n" +
        "ETRO,ETRO,エトロ,カスタム名詞\n" +
        "Ezumi,Ezumi,エズミ,カスタム名詞\n" +
        "F-LAGSTUF-F,F-LAGSTUF-F,フラグスタッフ,カスタム名詞\n" +
        "FABIANAFILIPPI,FABIANAFILIPPI,ファビアナフィリッピ,カスタム名詞\n" +
        "FACETASM,FACETASM,ファセッタズム,カスタム名詞\n" +
        "FACTOTUM,FACTOTUM,ファクトタム,カスタム名詞\n" +
        "FAGASSENT,FAGASSENT,ファガッサント,カスタム名詞\n" +
        "FalieroSarti,FalieroSarti,ファリエロサルティ,カスタム名詞\n" +
        "FENDI,FENDI,フェンディ,カスタム名詞\n" +
        "Ferragamo,Ferragamo,フェラガモ,カスタム名詞\n" +
        "Ferrari,Ferrari,フェラーリ,カスタム名詞\n" +
        "FILA,FILA,フィラ,カスタム名詞\n" +
        "FILLTHEBILL,FILLTHEBILL,フィルザビル,カスタム名詞\n" +
        "FilMelange,FilMelange,フィルメランジュ,カスタム名詞\n" +
        "FIVEISM×THREE,FIVEISM×THREE,ファイブイズムスリー,カスタム名詞\n" +
        "FLICKA,FLICKA,フリカ,カスタム名詞\n" +
        "FLUMOR,FLUMOR,フルモア,カスタム名詞\n" +
        "footthecoacher,footthecoacher,フットザコーチャー,カスタム名詞\n" +
        "FOOTSTOCKORIGINALS,FOOTSTOCKORIGINALS,フットストックオリジナルズ,カスタム名詞\n" +
        "forte_forte,forte_forte,フォルテフォルテ,カスタム名詞\n" +
        "fragmentdesign,fragmentdesign,フラグメントデザイン,カスタム名詞\n" +
        "Francfranc,Francfranc,フランフラン,カスタム名詞\n" +
        "Frank&Eileen,Frank&Eileen,フランクアンドアイリーン,カスタム名詞\n" +
        "FRANKLEDER,FRANKLEDER,フランクリーダー,カスタム名詞\n" +
        "FRAPBOIS,FRAPBOIS,フラップボワ,カスタム名詞\n" +
        "FRAYI.D,FRAYI.D,フレイアイディー,カスタム名詞\n" +
        "FREDPERRY,FREDPERRY,フレッドペリー,カスタム名詞\n" +
        "FUJI,FUJI,フジ,カスタム名詞\n" +
        "Fulton,Fulton,フルトン,カスタム名詞\n" +
        "FUMIETANAKA,FUMIETANAKA,フミエタナカ,カスタム名詞\n" +
        "FUMIKA_UCHIDA,FUMIKA_UCHIDA,フミカウチダ,カスタム名詞\n" +
        "FUMITOGANRYU,FUMITOGANRYU,フミトガンリュウ,カスタム名詞\n" +
        "FURFUR,FURFUR,ファーファー,カスタム名詞\n" +
        "FURLA,FURLA,フルラ,カスタム名詞\n" +
        "G-SHOCK,G-SHOCK,ジーショック,カスタム名詞\n" +
        "G-StarRAW,G-StarRAW,ジースターロウ,カスタム名詞\n" +
        "G.V.G.V.,G.V.G.V.,ジーブイジーヴィー,カスタム名詞\n" +
        "GalaabenD,GalaabenD,ガラアベンド,カスタム名詞\n" +
        "GANZO,GANZO,ガンゾ,カスタム名詞\n" +
        "GAP,GAP,ギャップ,カスタム名詞\n" +
        "gelatopique,gelatopique,ジェラートピケ,カスタム名詞\n" +
        "giab’sARCHIVIO,giab’sARCHIVIO,ジャブスアーカイヴィオ,カスタム名詞\n" +
        "GIANFRANCOFERRE,GIANFRANCOFERRE,ジャンフランコフェレ,カスタム名詞\n" +
        "GINORI1735,GINORI1735,ジノリ1735,カスタム名詞\n" +
        "GionTsujiri,GionTsujiri,ギオンツジリ,カスタム名詞\n" +
        "GiorgioArmani,GiorgioArmani,ジョルジオアルマーニ,カスタム名詞\n" +
        "GIORGIOBRATO,GIORGIOBRATO,ジョルジオブラート,カスタム名詞\n" +
        "GIUSEPPEZANOTTI,GIUSEPPEZANOTTI,ジュゼッペザノッティ,カスタム名詞\n" +
        "Givenchy,Givenchy,ジバンシィ,カスタム名詞\n" +
        "glamb,glamb,グラム,カスタム名詞\n" +
        "GLOBE-TROTTER,GLOBE-TROTTER,グローブトロッター,カスタム名詞\n" +
        "GODIVA,GODIVA,ゴディバ,カスタム名詞\n" +
        "GOLDENGOOSEDELUXEBRAND,GOLDENGOOSEDELUXEBRAND,ゴールデングースデラックスブランド,カスタム名詞\n" +
        "gomme,gomme,ゴム,カスタム名詞\n" +
        "GoshaRubchinskiy,GoshaRubchinskiy,ゴーシャラブチンスキー,カスタム名詞\n" +
        "Goutal,Goutal,グータル,カスタム名詞\n" +
        "GOYARD,GOYARD,ゴヤール,カスタム名詞\n" +
        "GRACECONTINENTAL,GRACECONTINENTAL,グレースコンチネンタル,カスタム名詞\n" +
        "GRAFF,GRAFF,グラフ,カスタム名詞\n" +
        "Graphpaper,Graphpaper,グラフペーパー,カスタム名詞\n" +
        "GREGORY,GREGORY,グレゴリー,カスタム名詞\n" +
        "GU,GU,ジーユー,カスタム名詞\n" +
        "GUACAMOLE,GUACAMOLE,グアカモーレ,カスタム名詞\n" +
        "GUCCI,GUCCI,グッチ,カスタム名詞\n" +
        "GUERLAIN,GUERLAIN,ゲラン,カスタム名詞\n" +
        "GUESS,GUESS,ゲス,カスタム名詞\n" +
        "GUIDI,GUIDI,グイディ,カスタム名詞\n" +
        "H&M,H&M,エイチアンドエム,カスタム名詞\n" +
        "h.NAOTO,h.NAOTO,エイチナオト,カスタム名詞\n" +
        "ha|za|ma,ha|za|ma,ハザマ,カスタム名詞\n" +
        "Haagen-Dazs,Haagen-Dazs,ハーゲンダッツ,カスタム名詞\n" +
        "HaaT,HaaT,ハート,カスタム名詞\n" +
        "HACCI,HACCI,ハッチ,カスタム名詞\n" +
        "HAIDERACKERMANN,HAIDERACKERMANN,ハイダーアッカーマン,カスタム名詞\n" +
        "HappySocks,HappySocks,ハッピーソックス,カスタム名詞\n" +
        "HARE,HARE,ハレ,カスタム名詞\n" +
        "Harikae,Harikae,ハリカエ,カスタム名詞\n" +
        "HARRYWINSTON,HARRYWINSTON,ハリーウィンストン,カスタム名詞\n" +
        "HARUNOBUMURATA,HARUNOBUMURATA,ハルノブムラタ,カスタム名詞\n" +
        "HATRA,HATRA,ハトラ,カスタム名詞\n" +
        "HAVERSACK,HAVERSACK,ハヴァサック,カスタム名詞\n" +
        "HELENKAMINSKI,HELENKAMINSKI,ヘレンカミンスキー,カスタム名詞\n" +
        "HELENARUBINSTEIN,HELENARUBINSTEIN,ヘレナルビンスタイン,カスタム名詞\n" +
        "HenderScheme,HenderScheme,ヘンダースキーマ,カスタム名詞\n" +
        "HenriCharpentier,HenriCharpentier,アンリシャルパンティエ,カスタム名詞\n" +
        "HENRILEROUX,HENRILEROUX,アンリルー,カスタム名詞\n" +
        "HENRIKVIBSKOV,HENRIKVIBSKOV,ヘンリックヴィブスコフ,カスタム名詞\n" +
        "HERMES,HERMES,エルメス,カスタム名詞\n" +
        "HERNO,HERNO,ヘルノ,カスタム名詞\n" +
        "HERONPRESTON,HERONPRESTON,ヘロンプレストン,カスタム名詞\n" +
        "HIROFU,HIROFU,ヒロフ,カスタム名詞\n" +
        "HIROKOBIS,HIROKOBIS,ヒロコビス,カスタム名詞\n" +
        "HIROKOKOSHINO,HIROKOKOSHINO,ヒロココシノ,カスタム名詞\n" +
        "HISUIHIROKOITO,HISUIHIROKOITO,ヒスイヒロコイトウ,カスタム名詞\n" +
        "HOLIDAY,HOLIDAY,ホリデイ,カスタム名詞\n" +
        "HOLZWEILER,HOLZWEILER,ホルツヴァイラー,カスタム名詞\n" +
        "HTC,HTC,エイチティーシー,カスタム名詞\n" +
        "HUBLOT,HUBLOT,ウブロ,カスタム名詞\n" +
        "HUF,HUF,ハフ,カスタム名詞\n" +
        "HUGOBOSS,HUGOBOSS,ヒューゴボス,カスタム名詞\n" +
        "HUNTER,HUNTER,ハンター,カスタム名詞\n" +
        "HUNTINGWORLD,HUNTINGWORLD,ハンティングワールド,カスタム名詞\n" +
        "HYKE,HYKE,ハイク,カスタム名詞\n" +
        "HYSTERICGLAMOUR,HYSTERICGLAMOUR,ヒステリックグラマー,カスタム名詞\n" +
        "Ice-Watch,Ice-Watch,アイスウォッチ,カスタム名詞\n" +
        "IDDAILYWEAR,IDDAILYWEAR,IDデイリーウェア,カスタム名詞\n" +
        "IKEA,IKEA,イケア,カスタム名詞\n" +
        "IKUMI,IKUMI,イクミ,カスタム名詞\n" +
        "ILBISONTE,ILBISONTE,イルビゾンテ,カスタム名詞\n" +
        "IN-PROCESSTokyo,IN-PROCESSTokyo,インプロセストウキョウ,カスタム名詞\n" +
        "INCOTEX,INCOTEX,インコテックス,カスタム名詞\n" +
        "INDIVIDUALIZEDSHIRTS,INDIVIDUALIZEDSHIRTS,インディビジュアライズドシャツ,カスタム名詞\n" +
        "INNAT,INNAT,イネート,カスタム名詞\n" +
        "INVERALLAN,INVERALLAN,インバララン,カスタム名詞\n" +
        "IPSA,IPSA,イプサ,カスタム名詞\n" +
        "Iroquois,Iroquois,イロコイ,カスタム名詞\n" +
        "ISABELMARANT,ISABELMARANT,イザベルマラン,カスタム名詞\n" +
        "ISAMUKATAYAMABACKLASH,ISAMUKATAYAMABACKLASH,イサムカタヤマバックラッシュ,カスタム名詞\n" +
        "ISSEYMIYAKE,ISSEYMIYAKE,イッセイミヤケ,カスタム名詞\n" +
        "IWC,IWC,アイダブリューシー,カスタム名詞\n" +
        "I’mhere:,I’mhere:,アイムヒア,カスタム名詞\n" +
        "J&MDAVIDSON,J&MDAVIDSON,ジェイアンドエムデイビッドソン,カスタム名詞\n" +
        "J.M.WESTON,J.M.WESTON,ジェイエムウェストン,カスタム名詞\n" +
        "JACOBCOHEN,JACOBCOHEN,ジェイコブコーエン,カスタム名詞\n" +
        "JAMHOMEMADE,JAMHOMEMADE,ジャムホームメイド,カスタム名詞\n" +
        "JAMESPERSE,JAMESPERSE,ジェームスパース,カスタム名詞\n" +
        "JaneMarple,JaneMarple,ジェーンマープル,カスタム名詞\n" +
        "JANESMITH,JANESMITH,ジェーンスミス,カスタム名詞\n" +
        "JASONWU,JASONWU,ジェイソンウー,カスタム名詞\n" +
        "JEANPAULGAULTIER,JEANPAULGAULTIER,ジャンポールゴルチエ,カスタム名詞\n" +
        "JEAN-PAULHEVIN,JEAN-PAULHEVIN,ジャンポールエヴァン,カスタム名詞\n" +
        "JeffreyCampbell,JeffreyCampbell,ジェフリーキャンベル,カスタム名詞\n" +
        "JennyFax,JennyFax,ジェニーファックス,カスタム名詞\n" +
        "Jens,Jens,イェンス,カスタム名詞\n" +
        "JieDa,JieDa,ジエダ,カスタム名詞\n" +
        "JILSANDER,JILSANDER,ジルサンダー,カスタム名詞\n" +
        "JILLSTUART,JILLSTUART,ジルスチュアート,カスタム名詞\n" +
        "JIMMYCHOO,JIMMYCHOO,ジミーチュウ,カスタム名詞\n" +
        "JINS,JINS,ジンズ,カスタム名詞\n" +
        "JOMALONELONDON,JOMALONELONDON,ジョーマローンロンドン,カスタム名詞\n" +
        "Jocomomola,Jocomomola,ジョコモモラ,カスタム名詞\n" +
        "JohnGalliano,JohnGalliano,ジョンガリアーノ,カスタム名詞\n" +
        "JOHNLAWRENCESULLIVAN,JOHNLAWRENCESULLIVAN,ジョンローレンスサリバン,カスタム名詞\n" +
        "JOHNLOBB,JOHNLOBB,ジョンロブ,カスタム名詞\n" +
        "JOHNMASONSMITH,JOHNMASONSMITH,ジョンメイスンスミス,カスタム名詞\n" +
        "johnmastersorganics,johnmastersorganics,ジョンマスターオーガニクス,カスタム名詞\n" +
        "JOHNSMEDLEY,JOHNSMEDLEY,ジョンスメドレー,カスタム名詞\n" +
        "JOHNBULL,JOHNBULL,ジョンブル,カスタム名詞\n" +
        "JohnstonsofElgin,JohnstonsofElgin,ジョンストンズオブエルギン,カスタム名詞\n" +
        "JOSEPHHOMME,JOSEPHHOMME,ジョセフオム,カスタム名詞\n" +
        "JOTAROSAITO,JOTAROSAITO,ジョータロウサイトウ,カスタム名詞\n" +
        "JOURNALSTANDARD,JOURNALSTANDARD,ジャーナルスタンダード,カスタム名詞\n" +
        "JUHA,JUHA,ジュハ,カスタム名詞\n" +
        "JulienDavid,JulienDavid,ジュリアンデビッド,カスタム名詞\n" +
        "JULIUS,JULIUS,ジュリウス,カスタム名詞\n" +
        "junhashimoto,junhashimoto,ジュンハシモト,カスタム名詞\n" +
        "JUNYAWATANABE,JUNYAWATANABE,ジュンヤワタナベ,カスタム名詞\n" +
        "JustCavalli,JustCavalli,ジャストカヴァリ,カスタム名詞\n" +
        "JUUN.J,JUUN.J,ジュンジェイ,カスタム名詞\n" +
        "JUVENILEHALLROLLCALL,JUVENILEHALLROLLCALL,ジュブナイルホールロールコール,カスタム名詞\n" +
        "JWAnderson,JWAnderson,ジェイダブリューアンダーソン,カスタム名詞\n" +
        "k3&co.,k3&co.,ケースリーコー,カスタム名詞\n" +
        "KAMILi,KAMILi,カミリ,カスタム名詞\n" +
        "KAMISHIMACHINAMI,KAMISHIMACHINAMI,カミシマチナミ,カスタム名詞\n" +
        "KANAKOSAKAI,KANAKOSAKAI,カナコサカイ,カスタム名詞\n" +
        "KANEBO,KANEBO,カネボウ,カスタム名詞\n" +
        "Kappa,Kappa,カッパ,カスタム名詞\n" +
        "KARENWALKER,KARENWALKER,カレンウォーカー,カスタム名詞\n" +
        "karrimor,karrimor,カリマー,カスタム名詞\n" +
        "KATE,KATE,ケイト,カスタム名詞\n" +
        "katespadenewyork,katespadenewyork,ケイトスペードニューヨーク,カスタム名詞\n" +
        "KazukiNagayama,KazukiNagayama,カズキナガヤマ,カスタム名詞\n" +
        "KAZUYUKIKUMAGAI,KAZUYUKIKUMAGAI,カズユキクマガイ,カスタム名詞\n" +
        "KEISUKEYOSHIDA,KEISUKEYOSHIDA,ケイスケヨシダ,カスタム名詞\n" +
        "KEITAMARUYAMA,KEITAMARUYAMA,ケイタマルヤマ,カスタム名詞\n" +
        "KENZO,KENZO,ケンゾー,カスタム名詞\n" +
        "KICSDOCUMENT.,KICSDOCUMENT.,キックスドキュメント,カスタム名詞\n" +
        "KIDILL,KIDILL,キディル,カスタム名詞\n" +
        "KIEHL'SSINCE1851,KIEHL'SSINCE1851,キールズシンス1851,カスタム名詞\n" +
        "KIIT,KIIT,キイト,カスタム名詞\n" +
        "KIJIMATAKAYUKI,KIJIMATAKAYUKI,キジマタカユキ,カスタム名詞\n" +
        "KINO,KINO,キノ,カスタム名詞\n" +
        "Kirov,Kirov,キロフ,カスタム名詞\n" +
        "KITH,KITH,キス,カスタム名詞\n" +
        "Kiwanda,Kiwanda,キワンダ,カスタム名詞\n" +
        "KOCHE,KOCHE,コシュ,カスタム名詞\n" +
        "kolor,kolor,カラー,カスタム名詞\n" +
        "KOTONA,KOTONA,コトナ,カスタム名詞\n" +
        "KRIZIA,KRIZIA,クリツィア,カスタム名詞\n" +
        "kujaku,kujaku,クジャク,カスタム名詞\n" +
        "KURO,KURO,クロ,カスタム名詞\n" +
        "K三,K三,ケイサン,カスタム名詞\n" +
        "L'OCCITANE,L'OCCITANE,ロクシタン,カスタム名詞\n" +
        "LAMAISONDUCHOCOLAT,LAMAISONDUCHOCOLAT,ラメゾンデュショコラ,カスタム名詞\n" +
        "LACOSTE,LACOSTE,ラコステ,カスタム名詞\n" +
        "LADMUSICIAN,LADMUSICIAN,ラッドミュージシャン,カスタム名詞\n" +
        "Laduree,Laduree,ラデュレ,カスタム名詞\n" +
        "Laline,Laline,ラリン,カスタム名詞\n" +
        "LANCOME,LANCOME,ランコム,カスタム名詞\n" +
        "LANVIN,LANVIN,ランバン,カスタム名詞\n" +
        "LANVINCOLLECTION,LANVINCOLLECTION,ランバンコレクション,カスタム名詞\n" +
        "LANVINenBleu,LANVINenBleu,ランバンオンブルー,カスタム名詞\n" +
        "LAPS,LAPS,ラップス,カスタム名詞\n" +
        "LARDINI,LARDINI,ラルディーニ,カスタム名詞\n" +
        "lauramercier,lauramercier,ローラメルシエ,カスタム名詞\n" +
        "Lautashi,Lautashi,ラウタシ,カスタム名詞\n" +
        "LeCreuset,LeCreuset,ル・クルーゼ,カスタム名詞\n" +
        "Lee,Lee,リー,カスタム名詞\n" +
        "LEH,LEH,レー,カスタム名詞\n" +
        "Leilian,Leilian,レイリアン,カスタム名詞\n" +
        "LEMAIRE,LEMAIRE,ルメール,カスタム名詞\n" +
        "LEONARD,LEONARD,レオナール,カスタム名詞\n" +
        "LeSportsac,LeSportsac,レスポートサック,カスタム名詞\n" +
        "leurlogette,leurlogette,ルールロジェット,カスタム名詞\n" +
        "LEVERCOUTURE,LEVERCOUTURE,リーバーコウチャ,カスタム名詞\n" +
        "Levi's,Levi's,リーバイス,カスタム名詞\n" +
        "Levi'sVintageClothing,Levi'sVintageClothing,リーバイスヴィンテージクロージング,カスタム名詞\n" +
        "LIAMHODGES,LIAMHODGES,リアムホッジス,カスタム名詞\n" +
        "Liberty,Liberty,リバティ,カスタム名詞\n" +
        "LIBERUM,LIBERUM,リベルム,カスタム名詞\n" +
        "LichtBestreben,LichtBestreben,リヒトベシュトレーベン,カスタム名詞\n" +
        "LIMIfeu,LIMIfeu,リミフゥ,カスタム名詞\n" +
        "LISSAGE,LISSAGE,リサージュ,カスタム名詞\n" +
        "LITTLEBIG,LITTLEBIG,リトルビッグ,カスタム名詞\n" +
        "LOEWE,LOEWE,ロエベ,カスタム名詞\n" +
        "LOKITHO,LOKITHO,ロキト,カスタム名詞\n" +
        "LONGCHAMP,LONGCHAMP,ロンシャン,カスタム名詞\n" +
        "LONGINES,LONGINES,ロンジン,カスタム名詞\n" +
        "LoroPiana,LoroPiana,ロロピアーナ,カスタム名詞\n" +
        "lotholon,lotholon,ロットホロン,カスタム名詞\n" +
        "LOUISVUITTON,LOUISVUITTON,ルイヴィトン,カスタム名詞\n" +
        "LOUNGELIZARD,LOUNGELIZARD,ラウンジリザード,カスタム名詞\n" +
        "lucienpellat-finet,lucienpellat-finet,リュシアンペラフィネ,カスタム名詞\n" +
        "LUIGIBORRELLI,LUIGIBORRELLI,ルイジボレリ,カスタム名詞\n" +
        "LUNASOL,LUNASOL,ルナソル,カスタム名詞\n" +
        "LUSH,LUSH,ラッシュ,カスタム名詞\n" +
        "N.HOOLYWOOD,N.HOOLYWOOD,エヌハリウッド,カスタム名詞\n" +
        "N21,N21,エヌニジュウイチ,カスタム名詞\n" +
        "NAIFE,NAIFE,ナイフ,カスタム名詞\n" +
        "NAILSINC,NAILSINC,ネイルズインク,カスタム名詞\n" +
        "NAISSANCE,NAISSANCE,ネサンス,カスタム名詞\n" +
        "Name.,Name.,ネーム,カスタム名詞\n" +
        "nanamica,nanamica,ナナミカ,カスタム名詞\n" +
        "NANGA,NANGA,ナンガ,カスタム名詞\n" +
        "NARS,NARS,ナーズ,カスタム名詞\n" +
        "Ne-net,Ne-net,ネネット,カスタム名詞\n" +
        "near.nippon,near.nippon,ニアニッポン,カスタム名詞\n" +
        "NEEDLES,NEEDLES,ニードルズ,カスタム名詞\n" +
        "NEHERA,NEHERA,ネヘラ,カスタム名詞\n" +
        "NEIGHBORHOOD,NEIGHBORHOOD,ネイバーフッド,カスタム名詞\n" +
        "NeilBarrett,NeilBarrett,ニールバレット,カスタム名詞\n" +
        "NEONSIGN,NEONSIGN,ネオンサイン,カスタム名詞\n" +
        "nEsessaire,nEsessaire,ネセセール,カスタム名詞\n" +
        "NewBalance,NewBalance,ニューバランス,カスタム名詞\n" +
        "NEWERA,NEWERA,ニューエラ,カスタム名詞\n" +
        "NICENESS,NICENESS,ナイスネス,カスタム名詞\n" +
        "NicolaiBergmannFlowers&Design,NicolaiBergmannFlowers&Design,ニコライバーグマンフラワーズアンドデザイン,カスタム名詞\n" +
        "NigelCabourn,NigelCabourn,ナイジェルカボーン,カスタム名詞\n" +
        "NIKE,NIKE,ナイキ,カスタム名詞\n" +
        "nikoand...,nikoand...,ニコアンド,カスタム名詞\n" +
        "NILøS,NILøS,ニルス,カスタム名詞\n" +
        "NINARICCI,NINARICCI,ニナリッチ,カスタム名詞\n" +
        "NIWAKA,NIWAKA,ニワカ,カスタム名詞\n" +
        "NIXON,NIXON,ニクソン,カスタム名詞\n" +
        "noirkeininomiya,noirkeininomiya,ノワールケイニノミヤ,カスタム名詞\n" +
        "NONTOKYO,NONTOKYO,ノン,カスタム名詞\n" +
        "nonnative,nonnative,ノンネイティブ,カスタム名詞\n" +
        "NorwegianRain,NorwegianRain,ノルウェージャンレイン,カスタム名詞\n" +
        "nude:masahikomaruyama,nude:masahikomaruyama,ヌードマサヒコマルヤマ,カスタム名詞\n" +
        "nuterm,nuterm,ニュターム,カスタム名詞\n" +
        "NYA-,NYA-,ニャー,カスタム名詞\n" +
        "Oproject,Oproject,オープロジェクト,カスタム名詞\n" +
        "OAMC,OAMC,オーエーエムシー,カスタム名詞\n" +
        "OFF-WHITE,OFF-WHITE,オフホワイト,カスタム名詞\n" +
        "OFFICINEUNIVERSELLEBULY,OFFICINEUNIVERSELLEBULY,オフィシーヌユニヴェルセルブリー,カスタム名詞\n" +
        "ohta,ohta,オオタ,カスタム名詞\n" +
        "OKIRAKU,OKIRAKU,オキラク,カスタム名詞\n" +
        "OLIVERGOLDSMITH,OLIVERGOLDSMITH,オリバーゴールドスミス,カスタム名詞\n" +
        "OLIVERPEOPLES,OLIVERPEOPLES,オリバーピープルズ,カスタム名詞\n" +
        "OLIVIABURTON,OLIVIABURTON,オリビアバートン,カスタム名詞\n" +
        "OMEGA,OMEGA,オメガ,カスタム名詞\n" +
        "OnitsukaTiger,OnitsukaTiger,オニツカタイガー,カスタム名詞\n" +
        "OPENINGCEREMONY,OPENINGCEREMONY,オープニングセレモニー,カスタム名詞\n" +
        "OPERA,OPERA,オペラ,カスタム名詞\n" +
        "OscardelaRenta,OscardelaRenta,オスカーデラレンタ,カスタム名詞\n" +
        "OVERCOAT,OVERCOAT,オーバーコート,カスタム名詞\n" +
        "PABLO,PABLO,パブロ,カスタム名詞\n" +
        "pacorabanne,pacorabanne,パコラバンヌ,カスタム名詞\n" +
        "Padmore&Barnes,Padmore&Barnes,パドモアアンドバーンズ,カスタム名詞\n" +
        "PALACESKATEBOARDS,PALACESKATEBOARDS,パレススケートボード,カスタム名詞\n" +
        "PalmAngels,PalmAngels,パームエンジェルス,カスタム名詞\n" +
        "PAMEOPOSE,PAMEOPOSE,パメオポーズ,カスタム名詞\n" +
        "PAÑPURI,PAÑPURI,パンプリ,カスタム名詞\n" +
        "Paratiisi,Paratiisi,パラティシ,カスタム名詞\n" +
        "pasdecalais,pasdecalais,パドカレ,カスタム名詞\n" +
        "PASSTHEBATON,PASSTHEBATON,パスザバトン,カスタム名詞\n" +
        "Patagonia,Patagonia,パタゴニア,カスタム名詞\n" +
        "PatekPhilippe,PatekPhilippe,パテックフィリップ,カスタム名詞\n" +
        "pAtisserieSadaharuAOKIparis,pAtisserieSadaharuAOKIparis,パティスリーサダハルアオキパリ,カスタム名詞\n" +
        "Patou,Patou,パトゥ,カスタム名詞\n" +
        "PAUL&JOE,PAUL&JOE,ポールアンドジョー,カスタム名詞\n" +
        "PaulSmith,PaulSmith,ポールスミス,カスタム名詞\n" +
        "PaulStuart,PaulStuart,ポールスチュアート,カスタム名詞\n" +
        "PAULEKA,PAULEKA,ポールカ,カスタム名詞\n" +
        "PEACHJOHN,PEACHJOHN,ピーチジョン,カスタム名詞\n" +
        "PELLICO,PELLICO,ペリーコ,カスタム名詞\n" +
        "PENHALIGON'S,PENHALIGON'S,ペンハリガンズ,カスタム名詞\n" +
        "PETITBATEAU,PETITBATEAU,プチバトー,カスタム名詞\n" +
        "PHEENY,PHEENY,フィーニー,カスタム名詞\n" +
        "PHILIPPEMODEL,PHILIPPEMODEL,フィリップモデル,カスタム名詞\n" +
        "PHILOSOPHY,PHILOSOPHY,フィロソフィ,カスタム名詞\n" +
        "PHINGERIN,PHINGERIN,フィンガリン,カスタム名詞\n" +
        "PhoebePhilo,PhoebePhilo,フィービーフィロ,カスタム名詞\n" +
        "PierreCardin,PierreCardin,ピエールカルダン,カスタム名詞\n" +
        "PIERREHARDY,PIERREHARDY,ピエールアルディ,カスタム名詞\n" +
        "PIERREHERMEPARIS,PIERREHERMEPARIS,ピエールエルメパリ,カスタム名詞\n" +
        "PierreMarcolini,PierreMarcolini,ピエールマルコリーニ,カスタム名詞\n" +
        "PIGALLE,PIGALLE,ピガール,カスタム名詞\n" +
        "pillings,pillings,ピリングス,カスタム名詞\n" +
        "POLA,POLA,ポーラ,カスタム名詞\n" +
        "PORTER,PORTER,ポーター,カスタム名詞\n" +
        "PORTS1961,PORTS1961,ポーツ1961,カスタム名詞\n" +
        "PRADA,PRADA,プラダ,カスタム名詞\n" +
        "PRDXPARADOXTOKYO,PRDXPARADOXTOKYO,プロデューサーパラドックストーキョー,カスタム名詞\n" +
        "Primavista,Primavista,プリマヴィスタ,カスタム名詞\n" +
        "PringleofScotland,PringleofScotland,プリングルオブスコットランド,カスタム名詞\n" +
        "ProenzaSchouler,ProenzaSchouler,プロエンザスクーラー,カスタム名詞\n" +
        "PUMA,PUMA,プーマ,カスタム名詞\n" +
        "Q-pot.,Q-pot.,キューポット,カスタム名詞\n" +
        "Qu'ilfaitbon,Qu'ilfaitbon,キュフェボン,カスタム名詞\n" +
        "rag&bone,rag&bone,ラグアンドボーン,カスタム名詞\n" +
        "RAINMAKER,RAINMAKER,レインメーカー,カスタム名詞\n" +
        "RalphLauren,RalphLauren,ラルフローレン,カスタム名詞\n" +
        "Rawtus,Rawtus,ロータス,カスタム名詞\n" +
        "RayBEAMS,RayBEAMS,レイビームス,カスタム名詞\n" +
        "Ray-Ban,Ray-Ban,レイバン,カスタム名詞\n" +
        "RBTXCO/RETAK_,RBTXCO/RETAK_,アールビーティーエックスシーオー/リタック,カスタム名詞\n" +
        "READYMADE,READYMADE,レディメイド,カスタム名詞\n" +
        "Reebok,Reebok,リーボック,カスタム名詞\n" +
        "REGAL,REGAL,リーガル,カスタム名詞\n" +
        "REKISAMI,REKISAMI,レキサミ,カスタム名詞\n" +
        "Repetto,Repetto,レペット,カスタム名詞\n" +
        "REVLON,REVLON,レブロン,カスタム名詞\n" +
        "RickOwens,RickOwens,リックオウエンス,カスタム名詞\n" +
        "RIMMEL,RIMMEL,リンメル,カスタム名詞\n" +
        "RIMOWA,RIMOWA,リモワ,カスタム名詞\n" +
        "RIPVANWINKLE,RIPVANWINKLE,リップヴァンウィンクル,カスタム名詞\n" +
        "RMK,RMK,アールエムケー,カスタム名詞\n" +
        "rmsbeauty,rmsbeauty,アールエムエスビューティー,カスタム名詞\n" +
        "roarguns,roarguns,ロアーガンズ,カスタム名詞\n" +
        "robertocavalli,robertocavalli,ロベルトカヴァリ,カスタム名詞\n" +
        "robertocollina,robertocollina,ロベルトコリーナ,カスタム名詞\n" +
        "robes&confections,robes&confections,ローブアンドコンフェクションズ,カスタム名詞\n" +
        "ROCHAS,ROCHAS,ロシャス,カスタム名詞\n" +
        "Roen,Roen,ロエン,カスタム名詞\n" +
        "RogerVivier,RogerVivier,ロジェヴィヴィエ,カスタム名詞\n" +
        "ROGER&GALLET,ROGER&GALLET,ロジェアンドギャレット,カスタム名詞\n" +
        "ROLEX,ROLEX,ロレックス,カスタム名詞\n" +
        "RonHerman,RonHerman,ロンハーマン,カスタム名詞\n" +
        "Roomno.8,Roomno.8,ルームナンバーエイト,カスタム名詞\n" +
        "RoyalCopenhagen,RoyalCopenhagen,ロイヤルコペンハーゲン,カスタム名詞\n" +
        "RPKO,RPKO,アールピーケーオー,カスタム名詞\n" +
        "RUMBLERED,RUMBLERED,ランブルレッド,カスタム名詞\n" +
        "S.T.Dupont,S.T.Dupont,エスティデュポン,カスタム名詞\n" +
        "SABON,SABON,サボン,カスタム名詞\n" +
        "sacai,sacai,サカイ,カスタム名詞\n" +
        "SAGEDECRET,SAGEDECRET,サージュドクレール,カスタム名詞\n" +
        "sakayori.,sakayori.,サカヨリ,カスタム名詞\n" +
        "SalvatorePiccolo,SalvatorePiccolo,サルヴァトーレピッコロ,カスタム名詞\n" +
        "salvy;,salvy;,サルビー,カスタム名詞\n" +
        "Samsonite,Samsonite,サムソナイト,カスタム名詞\n" +
        "Samuji,Samuji,サムジ,カスタム名詞\n" +
        "SANTONI,SANTONI,サントーニ,カスタム名詞\n" +
        "SANUA,SANUA,サヌア,カスタム名詞\n" +
        "Sasquatchfabrix.,Sasquatchfabrix.,サスクォッチファブリックス,カスタム名詞\n" +
        "SATOKOOZAWA,SATOKOOZAWA,サトコオザワ,カスタム名詞\n" +
        "SATORUSASAKI,SATORUSASAKI,サトルササキ,カスタム名詞\n" +
        "SaturdaysNYC,SaturdaysNYC,サタデーズニューヨークシティ,カスタム名詞\n" +
        "SAYAKADAVIS,SAYAKADAVIS,サヤカデイビス,カスタム名詞\n" +
        "SCAPA,SCAPA,スカパ,カスタム名詞\n" +
        "SCOTCHGRAIN,SCOTCHGRAIN,スコッチグレイン,カスタム名詞\n" +
        "Scye,Scye,サイ,カスタム名詞\n" +
        "SeeByChloE,SeeByChloE,シーバイクロエ,カスタム名詞\n" +
        "SEIKO,SEIKO,セイコー,カスタム名詞\n" +
        "semoh,semoh,セモー,カスタム名詞\n" +
        "SERGEdebleu,SERGEdebleu,セルジュドブルー,カスタム名詞\n" +
        "SergioRossi,SergioRossi,セルジオロッシ,カスタム名詞\n" +
        "SEVENBYSEVEN,SEVENBYSEVEN,セブンバイセブン,カスタム名詞\n" +
        "SHAREEF,SHAREEF,シャリーフ,カスタム名詞\n" +
        "SHETokyo,SHETokyo,シェトウキョウ,カスタム名詞\n" +
        "SHIATZYCHEN,SHIATZYCHEN,シャッツィチェン,カスタム名詞\n" +
        "SHIHARA,SHIHARA,シハラ,カスタム名詞\n" +
        "ShirleyTemple,ShirleyTemple,シャーリーテンプル,カスタム名詞\n" +
        "SHIRO,SHIRO,シロ,カスタム名詞\n" +
        "SHIROMA,SHIROMA,シロマ,カスタム名詞\n" +
        "SHISEIDO,SHISEIDO,資生堂,カスタム名詞\n" +
        "shuuemura,shuuemura,シュウウエムラ,カスタム名詞\n" +
        "SHURON,SHURON,シュロン,カスタム名詞\n" +
        "SISE,SISE,シセ,カスタム名詞\n" +
        "SK-II,SK-II,エスケーツー,カスタム名詞\n" +
        "sneeuw,sneeuw,スネウ,カスタム名詞\n" +
        "SNIDEL,SNIDEL,スナイデル,カスタム名詞\n" +
        "SnowPeak,SnowPeak,スノーピーク,カスタム名詞\n" +
        "soe,soe,ソエ,カスタム名詞\n" +
        "SOFTHYPHEN,SOFTHYPHEN,ソフトハイフン,カスタム名詞\n" +
        "SOMARTA,SOMARTA,ソマルタ,カスタム名詞\n" +
        "SOPHNET.,SOPHNET.,ソフネット,カスタム名詞\n" +
        "SOUTH2WEST8,SOUTH2WEST8,サウスツーウエストエイト,カスタム名詞\n" +
        "SPECTUSSHOECO.,SPECTUSSHOECO.,スペクタスシューコ,カスタム名詞\n" +
        "SPORTMAX,SPORTMAX,スポーツマックス,カスタム名詞\n" +
        "Sretsis,Sretsis,スレシス,カスタム名詞\n" +
        "STARJEWELRY,STARJEWELRY,スタージュエリー,カスタム名詞\n" +
        "Starbucks,Starbucks,スターバックス,カスタム名詞\n" +
        "StellaJean,StellaJean,ステラジーン,カスタム名詞\n" +
        "STELLAMcCARTNEY,STELLAMcCARTNEY,ステラマッカートニー,カスタム名詞\n" +
        "STEPHANSCHNEIDER,STEPHANSCHNEIDER,ステファンシュナイダー,カスタム名詞\n" +
        "STOF,STOF,ストフ,カスタム名詞\n" +
        "STONEISLAND,STONEISLAND,ストーンアイランド,カスタム名詞\n" +
        "STUDIONICHOLSON,STUDIONICHOLSON,スタジオニコルソン,カスタム名詞\n" +
        "STUDIOSEVEN,STUDIOSEVEN,ステュディオセブン,カスタム名詞\n" +
        "STUDIOUS,STUDIOUS,ステュディオス,カスタム名詞\n" +
        "STUSSY,STUSSY,ステューシー,カスタム名詞\n" +
        "SUGARHILL,SUGARHILL,シュガーヒル,カスタム名詞\n" +
        "SUICOKE,SUICOKE,スイコック,カスタム名詞\n" +
        "sulvam,sulvam,スルヴァム,カスタム名詞\n" +
        "SUNAOKUWAHARA,SUNAOKUWAHARA,スナオクワハラ,カスタム名詞\n" +
        "SUPP.,SUPP.,サップ,カスタム名詞\n" +
        "supportsurface,supportsurface,サポートサーフェス,カスタム名詞\n" +
        "Supreme,Supreme,シュプリーム,カスタム名詞\n" +
        "SUQQU,SUQQU,スック,カスタム名詞\n" +
        "suzukitakayuki,suzukitakayuki,スズキタカユキ,カスタム名詞\n" +
        "SWAROVSKI,SWAROVSKI,スワロフスキー,カスタム名詞\n" +
        "Swatch,Swatch,スウォッチ,カスタム名詞\n" +
        "Sybilla,Sybilla,シビラ,カスタム名詞\n" +
        "TAAKK,TAAKK,ターク,カスタム名詞\n" +
        "TADASHISHOJI,TADASHISHOJI,タダシショージ,カスタム名詞\n" +
        "TAEASHIDA,TAEASHIDA,タエアシダ,カスタム名詞\n" +
        "TAGHeuer,TAGHeuer,タグホイヤー,カスタム名詞\n" +
        "TAGLIATORE,TAGLIATORE,タリアトーレ,カスタム名詞\n" +
        "TAION,TAION,タイオン,カスタム名詞\n" +
        "TAKAHIROMIYASHITATheSoloist.,TAKAHIROMIYASHITATheSoloist.,タカヒロミヤシタザソロイスト,カスタム名詞\n" +
        "talkative,talkative,トーカティブ,カスタム名詞\n" +
        "TAN,TAN,タン,カスタム名詞\n" +
        "TANAKA,TANAKA,タナカ,カスタム名詞\n" +
        "TAO,TAO,タオ,カスタム名詞\n" +
        "TASAKI,TASAKI,タサキ,カスタム名詞\n" +
        "TATRAS,TATRAS,タトラス,カスタム名詞\n" +
        "TEÄTORA,TEÄTORA,テアトラ,カスタム名詞\n" +
        "Tenc,Tenc,テンシー,カスタム名詞\n" +
        "Tendence,Tendence,テンデンス,カスタム名詞\n" +
        "Teva,Teva,テバ,カスタム名詞\n" +
        "THEBODYSHOP,THEBODYSHOP,ザボディショップ,カスタム名詞\n" +
        "THEKEIJI,THEKEIJI,ザケイジ,カスタム名詞\n" +
        "TheLetters,TheLetters,ザレターズ,カスタム名詞\n" +
        "THENERDYS,THENERDYS,ザナーディーズ,カスタム名詞\n" +
        "THENORTHFACE,THENORTHFACE,ザノースフェイス,カスタム名詞\n" +
        "THEONITSUKA,THEONITSUKA,ザオニツカ,カスタム名詞\n" +
        "THERERACS,THERERACS,ザレラックス,カスタム名詞\n" +
        "THEROW,THEROW,ザロウ,カスタム名詞\n" +
        "TheViridi-anne,TheViridi-anne,ザヴィリディアン,カスタム名詞\n" +
        "THEATREPRODUCTS,THEATREPRODUCTS,シアタープロダクツ,カスタム名詞\n" +
        "Theory,Theory,セオリー,カスタム名詞\n" +
        "THOMBROWNE,THOMBROWNE,トムブラウン,カスタム名詞\n" +
        "THRAW,THRAW,スロウ,カスタム名詞\n" +
        "THREE,THREE,スリー,カスタム名詞\n" +
        "threedots,threedots,スリードッツ,カスタム名詞\n" +
        "tibi,tibi,ティビ,カスタム名詞\n" +
        "Tiffany&Co.,Tiffany&Co.,ティファニー,カスタム名詞\n" +
        "tiittokyo,tiittokyo,ティートトウキョウ,カスタム名詞\n" +
        "Timberland,Timberland,ティンバーランド,カスタム名詞\n" +
        "TINKERBELL,TINKERBELL,ティンカーベル,カスタム名詞\n" +
        "TOCCA,TOCCA,トッカ,カスタム名詞\n" +
        "TOD'S,TOD'S,トッズ,カスタム名詞\n" +
        "TOGA,TOGA,トーガ,カスタム名詞\n" +
        "TOMFORD,TOMFORD,トムフォード,カスタム名詞\n" +
        "TOMMYHILFIGER,TOMMYHILFIGER,トミーヒルフィガー,カスタム名詞\n" +
        "TOMOKOIZUMI,TOMOKOIZUMI,トモコイズミ,カスタム名詞\n" +
        "TOMORROWLAND,TOMORROWLAND,トゥモローランド,カスタム名詞\n" +
        "TOMWOOD,TOMWOOD,トムウッド,カスタム名詞\n" +
        "TOPMAN,TOPMAN,トップマン,カスタム名詞\n" +
        "TOPSHOP,TOPSHOP,トップショップ,カスタム名詞\n" +
        "TOPSHOPUNIQUE,TOPSHOPUNIQUE,トップショップユニーク,カスタム名詞\n" +
        "TORAYA,TORAYA,トラヤ,カスタム名詞\n" +
        "TORYBURCH,TORYBURCH,トリーバーチ,カスタム名詞\n" +
        "TraditionalWeatherwear,TraditionalWeatherwear,トラディショナルウェザーウェア,カスタム名詞\n" +
        "Tricker's,Tricker's,トリッカーズ,カスタム名詞\n" +
        "Triumph,Triumph,トリンフ,カスタム名詞\n" +
        "TROVE,TROVE,トローヴ,カスタム名詞\n" +
        "TRUSSARDI,TRUSSARDI,トラサルディ,カスタム名詞\n" +
        "TSUCHIYAKABAN,TSUCHIYAKABAN,ツチヤカバン,カスタム名詞\n" +
        "TSUMORICHISATO,TSUMORICHISATO,ツモリチサト,カスタム名詞\n" +
        "TULLY'SCOFFEE,TULLY'SCOFFEE,タリーズコーヒー,カスタム名詞\n" +
        "UGG,UGG,アグ,カスタム名詞\n" +
        "UJOH,UJOH,ウジョウ,カスタム名詞\n" +
        "uka,uka,ウカ,カスタム名詞\n" +
        "UNDECORATED,UNDECORATED,アンデコレイテッド,カスタム名詞\n" +
        "UNDEFEATED,UNDEFEATED,アンディフィーテッド,カスタム名詞\n" +
        "UNDERCOVER,UNDERCOVER,アンダーカバー,カスタム名詞\n" +
        "uniformexperiment,uniformexperiment,ユニフォームエクスペリメント,カスタム名詞\n" +
        "UNIQLO,UNIQLO,ユニクロ,カスタム名詞\n" +
        "UNITEDARROWS,UNITEDARROWS,ユナイテッドアローズ,カスタム名詞\n" +
        "UNITEDNUDE,UNITEDNUDE,ユナイテッドヌード,カスタム名詞\n" +
        "UNITEDSTANDARD,UNITEDSTANDARD,ユナイテッドスタンダード,カスタム名詞\n" +
        "UNITEDTOKYO,UNITEDTOKYO,ユナイテッドトウキョウ,カスタム名詞\n" +
        "UNITUS,UNITUS,ユニタス,カスタム名詞\n" +
        "UNUSED,UNUSED,アンユーズド,カスタム名詞\n" +
        "URBANRESEARCH,URBANRESEARCH,アーバンリサーチ,カスタム名詞\n" +
        "URU,URU,ウル,カスタム名詞\n" +
        "VACHERONCONSTANTIN,VACHERONCONSTANTIN,ヴァシュロン・コンスタンタン,カスタム名詞\n" +
        "VAINLARCHIVE,VAINLARCHIVE,ヴェイルアーカイブ,カスタム名詞\n" +
        "VALENTINO,VALENTINO,ヴァレンティノ,カスタム名詞\n" +
        "VALMONT,VALMONT,ヴァルモン,カスタム名詞\n" +
        "VanCleef&Arpels,VanCleef&Arpels,ヴァンクリーフ&アーペル,カスタム名詞\n" +
        "vanessabruno,vanessabruno,ヴァネッサブリューノ,カスタム名詞\n" +
        "VANS,VANS,ヴァンズ,カスタム名詞\n" +
        "VEIN,VEIN,ヴェイン,カスタム名詞\n" +
        "VENDOMEAOYAMA,VENDOMEAOYAMA,ヴァンドーム青山,カスタム名詞\n" +
        "Veritecoeur,Veritecoeur,ヴェリテクール,カスタム名詞\n" +
        "VERSACE,VERSACE,ヴェルサーチ,カスタム名詞\n" +
        "VersusVersace,VersusVersace,ヴェルサスヴェルサーチ,カスタム名詞\n" +
        "VETEMENTS,VETEMENTS,ヴェトモン,カスタム名詞\n" +
        "VICTIM,VICTIM,ヴィクティム,カスタム名詞\n" +
        "Visee,Visee,ヴィセ,カスタム名詞\n" +
        "visvim,visvim,ヴィズビム,カスタム名詞\n" +
        "VIVIANO,VIVIANO,ヴィビアーノ,カスタム名詞\n" +
        "VivienneWestwood,VivienneWestwood,ヴィヴィアンウエストウッド,カスタム名詞\n" +
        "WACKOMARIA,WACKOMARIA,ワコマリア,カスタム名詞\n" +
        "WACOAL,WACOAL,ワコール,カスタム名詞\n" +
        "WAKO,WAKO,ワコー,カスタム名詞\n" +
        "WEDGWOOD,WEDGWOOD,ウェッジウッド,カスタム名詞\n" +
        "WEWILL,WEWILL,ウィーウィル,カスタム名詞\n" +
        "WEYEP,WEYEP,ウェイエップ,カスタム名詞\n" +
        "WhiteMountaineering,WhiteMountaineering,ホワイトマウンテニアリング,カスタム名詞\n" +
        "WHIZLIMITED,WHIZLIMITED,ウィズリミテッド,カスタム名詞\n" +
        "wizzard,wizzard,ウィザード,カスタム名詞\n" +
        "wjk,wjk,ダブルジェイケイ,カスタム名詞\n" +
        "wonderland,wonderland,ワンダーランド,カスタム名詞\n" +
        "WOOLRICH,WOOLRICH,ウールリッチ,カスタム名詞\n" +
        "WRAPINKNOT,WRAPINKNOT,ラップインノット,カスタム名詞\n" +
        "X-girl,X-girl,エックスガール,カスタム名詞\n" +
        "XLARGE,XLARGE,エクストララージ,カスタム名詞\n" +
        "Y's,Y's,ワイズ,カスタム名詞\n" +
        "Y-3,Y-3,ワイスリー,カスタム名詞\n" +
        "YAECA,YAECA,ヤエカ,カスタム名詞\n" +
        "YEAHRIGHT!!,YEAHRIGHT!!,イェアーライト,カスタム名詞\n" +
        "YOHEIOHNO,YOHEIOHNO,ヨウヘイオオノ,カスタム名詞\n" +
        "YohjiYamamoto,YohjiYamamoto,ヨウジヤマモト,カスタム名詞\n" +
        "YOKE,YOKE,ヨーク,カスタム名詞\n" +
        "YOKOCHAN,YOKOCHAN,ヨウコチャン,カスタム名詞\n" +
        "yoshieinaba,yoshieinaba,ヨシエイナバ,カスタム名詞\n" +
        "yoshiokubo,yoshiokubo,ヨシオクボ,カスタム名詞\n" +
        "youozeki,youozeki,ユウオゼキ,カスタム名詞\n" +
        "yuhaku,yuhaku,ユハク,カスタム名詞\n" +
        "YUKI,YUKI,ユキ,カスタム名詞\n" +
        "YUKIHASHIMOTO,YUKIHASHIMOTO,ユキハシモト,カスタム名詞\n" +
        "YUKITORII,YUKITORII,ユキトリイ,カスタム名詞\n" +
        "YUKIHEROPRO-WRESTLING,YUKIHEROPRO-WRESTLING,ユキヒーロープロレスリング,カスタム名詞\n" +
        "YUMAKOSHINO,YUMAKOSHINO,ユウマコシノ,カスタム名詞\n" +
        "YVANVALENTIN,YVANVALENTIN,イヴァンヴァレンタン,カスタム名詞\n" +
        "YvesSaintLaurent,YvesSaintLaurent,イヴサンローラン,カスタム名詞\n" +
        "YvesSalomon,YvesSalomon,イヴサロモン,カスタム名詞\n" +
        "ZANELLATO,ZANELLATO,ザネラート,カスタム名詞\n" +
        "ZARA,ZARA,ザラ,カスタム名詞\n" +
        "ZEGNA,ZEGNA,ゼニア,カスタム名詞\n" +
        "ZEROHALLIBURTON,ZEROHALLIBURTON,ゼロハリバートン,カスタム名詞\n" +
        "Zoff,Zoff,ゾフ,カスタム名詞\n" +
        "ZUCCa,ZUCCa,ズッカ,カスタム名詞\n" +
        "08sircus,08sircus,ゼロエイトサーカス,カスタム名詞\n" +
        "1/2Un-Demi,1/2Un-Demi,イチニハンアンデミ,カスタム名詞\n" +
        "1017ALYX9SM,1017ALYX9SM,テンセブンアリクスナインエスエム,カスタム名詞\n" +
        "3.1PhillipLim,3.1PhillipLim,サンピョイチフィリップリム,カスタム名詞\n" +
        "5-knot.....,5-knot.....,ゴーカノット,カスタム名詞\n" +
        "999.9,999.9,キューキューキューテンキュー,カスタム名詞\n";
}
